# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent
import Extract_text
import librosa


class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(676, 485)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StackedWidget.sizePolicy().hasHeightForWidth())
        StackedWidget.setSizePolicy(sizePolicy)
        self.select = QtWidgets.QWidget()
        self.select.setObjectName("select")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.select)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.select)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.select)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_5.addWidget(self.comboBox, 1, 2, 1, 1)
        self.next0 = QtWidgets.QToolButton(self.select)
        self.next0.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../UI/res/next.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next0.setIcon(icon)
        self.next0.setIconSize(QtCore.QSize(30, 30))
        self.next0.setObjectName("next0")
        self.gridLayout_5.addWidget(self.next0, 1, 3, 1, 1)
        StackedWidget.addWidget(self.select)
        self.task1 = QtWidgets.QWidget()
        self.task1.setObjectName("task1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.task1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.previous1 = QtWidgets.QToolButton(self.task1)
        self.previous1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../UI/res/previous.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous1.setIcon(icon1)
        self.previous1.setIconSize(QtCore.QSize(30, 30))
        self.previous1.setObjectName("previous1")
        self.gridLayout_2.addWidget(self.previous1, 0, 0, 1, 1)
        self.next1 = QtWidgets.QToolButton(self.task1)
        self.next1.setText("")
        self.next1.setIcon(icon)
        self.next1.setIconSize(QtCore.QSize(30, 30))
        self.next1.setObjectName("next1")
        self.gridLayout_2.addWidget(self.next1, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.task1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 2)
        self.Article1 = QtWidgets.QTextBrowser(self.task1)
        self.Article1.setObjectName("Article1")
        self.gridLayout_2.addWidget(self.Article1, 1, 0, 1, 4)
        StackedWidget.addWidget(self.task1)
        self.task2 = QtWidgets.QWidget()
        self.task2.setObjectName("task2")
        self.gridLayout = QtWidgets.QGridLayout(self.task2)
        self.gridLayout.setObjectName("gridLayout")
        self.Slider2 = QtWidgets.QSlider(self.task2)
        self.Slider2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider2.setObjectName("Slider2")
        self.gridLayout.addWidget(self.Slider2, 2, 1, 1, 1)
        self.next2 = QtWidgets.QToolButton(self.task2)
        self.next2.setText("")
        self.next2.setIcon(icon)
        self.next2.setIconSize(QtCore.QSize(30, 30))
        self.next2.setObjectName("next2")
        self.gridLayout.addWidget(self.next2, 0, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.task2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 5)
        self.previous2 = QtWidgets.QToolButton(self.task2)
        self.previous2.setText("")
        self.previous2.setIcon(icon1)
        self.previous2.setIconSize(QtCore.QSize(30, 30))
        self.previous2.setObjectName("previous2")
        self.gridLayout.addWidget(self.previous2, 0, 0, 1, 1)
        self.Play2 = QtWidgets.QToolButton(self.task2)
        self.Play2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../UI/res/play_btn.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Play2.setIcon(icon2)
        self.Play2.setIconSize(QtCore.QSize(50, 50))
        self.Play2.setObjectName("Play2")
        self.gridLayout.addWidget(self.Play2, 2, 0, 1, 1)
        self.Transcript2 = QtWidgets.QTextBrowser(self.task2)
        self.Transcript2.setObjectName("Transcript2")
        self.gridLayout.addWidget(self.Transcript2, 1, 3, 1, 4)
        self.Press2 = QtWidgets.QToolButton(self.task2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../UI/res/right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("../UI/res/left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Press2.setIcon(icon3)
        self.Press2.setIconSize(QtCore.QSize(50, 50))
        self.Press2.setObjectName("Press2")
        self.gridLayout.addWidget(self.Press2, 2, 2, 1, 1)
        self.Article2 = QtWidgets.QTextBrowser(self.task2)
        self.Article2.setObjectName("Article2")
        self.gridLayout.addWidget(self.Article2, 1, 0, 1, 3)
        StackedWidget.addWidget(self.task2)
        self.task3 = QtWidgets.QWidget()
        self.task3.setObjectName("task3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.task3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Transcript3 = QtWidgets.QTextBrowser(self.task3)
        self.Transcript3.setObjectName("Transcript3")
        self.gridLayout_3.addWidget(self.Transcript3, 1, 4, 1, 2)
        self.previous3 = QtWidgets.QToolButton(self.task3)
        self.previous3.setText("")
        self.previous3.setIcon(icon1)
        self.previous3.setIconSize(QtCore.QSize(30, 30))
        self.previous3.setObjectName("previous3")
        self.gridLayout_3.addWidget(self.previous3, 0, 0, 1, 1)
        self.Slider3 = QtWidgets.QSlider(self.task3)
        self.Slider3.setOrientation(QtCore.Qt.Horizontal)
        self.Slider3.setObjectName("Slider3")
        self.gridLayout_3.addWidget(self.Slider3, 2, 1, 1, 2)
        self.Article3 = QtWidgets.QTextBrowser(self.task3)
        self.Article3.setObjectName("Article3")
        self.gridLayout_3.addWidget(self.Article3, 1, 0, 1, 4)
        self.Play3 = QtWidgets.QToolButton(self.task3)
        self.Play3.setText("")
        self.Play3.setIcon(icon2)
        self.Play3.setIconSize(QtCore.QSize(50, 50))
        self.Play3.setObjectName("Play3")
        self.gridLayout_3.addWidget(self.Play3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.task3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 1, 1, 4)
        self.Press3 = QtWidgets.QToolButton(self.task3)
        self.Press3.setIcon(icon3)
        self.Press3.setIconSize(QtCore.QSize(50, 50))
        self.Press3.setObjectName("Press3")
        self.gridLayout_3.addWidget(self.Press3, 2, 3, 1, 1)
        self.next3 = QtWidgets.QToolButton(self.task3)
        self.next3.setText("")
        self.next3.setIcon(icon)
        self.next3.setIconSize(QtCore.QSize(30, 30))
        self.next3.setObjectName("next3")
        self.gridLayout_3.addWidget(self.next3, 0, 5, 1, 1)
        StackedWidget.addWidget(self.task3)
        self.task4 = QtWidgets.QWidget()
        self.task4.setObjectName("task4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.task4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Transcript4 = QtWidgets.QTextBrowser(self.task4)
        self.Transcript4.setObjectName("Transcript4")
        self.gridLayout_4.addWidget(self.Transcript4, 2, 0, 1, 5)
        self.Play4 = QtWidgets.QToolButton(self.task4)
        self.Play4.setText("")
        self.Play4.setIcon(icon2)
        self.Play4.setIconSize(QtCore.QSize(50, 50))
        self.Play4.setObjectName("Play4")
        self.gridLayout_4.addWidget(self.Play4, 1, 0, 1, 2)
        self.Slider4 = QtWidgets.QSlider(self.task4)
        self.Slider4.setOrientation(QtCore.Qt.Horizontal)
        self.Slider4.setObjectName("Slider4")
        self.gridLayout_4.addWidget(self.Slider4, 1, 2, 1, 1)
        self.previous4 = QtWidgets.QToolButton(self.task4)
        self.previous4.setText("")
        self.previous4.setIcon(icon1)
        self.previous4.setIconSize(QtCore.QSize(30, 30))
        self.previous4.setObjectName("previous4")
        self.gridLayout_4.addWidget(self.previous4, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.task4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 1, 1, 2)
        self.next4 = QtWidgets.QToolButton(self.task4)
        self.next4.setEnabled(False)
        self.next4.setText("")
        self.next4.setIcon(icon)
        self.next4.setIconSize(QtCore.QSize(30, 30))
        self.next4.setObjectName("next4")
        self.gridLayout_4.addWidget(self.next4, 0, 4, 1, 1)
        self.Press4 = QtWidgets.QToolButton(self.task4)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../UI/res/down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("../UI/res/up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Press4.setIcon(icon4)
        self.Press4.setIconSize(QtCore.QSize(50, 50))
        self.Press4.setObjectName("Press4")
        self.gridLayout_4.addWidget(self.Press4, 1, 3, 1, 2)
        StackedWidget.addWidget(self.task4)

        self.retranslateUi(StackedWidget)
        StackedWidget.setCurrentIndex(0
                                      )
        self.Press2.toggled['bool'].connect(self.Transcript2.show)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)

        def show_transcript(btn, transcript_widget):
            if btn.isChecked():
                transcript_widget.show()
            else:
                transcript_widget.hide()

        self.Press2.setCheckable(True)
        action2 = lambda: show_transcript(self.Press2, self.Transcript2)
        self.Press2.clicked.connect(action2)
        self.Press3.setCheckable(True)
        action3 = lambda: show_transcript(self.Press3, self.Transcript3)
        self.Press3.clicked.connect(action3)
        self.Press4.setCheckable(True)
        action4 = lambda: show_transcript(self.Press4, self.Transcript4)
        self.Press4.clicked.connect(action4)

        self.index = 0

        def refresh(i):
            StackedWidget.setCurrentIndex(i)

        def Next():
            self.index += 1
            refresh(self.index)

        self.next0.clicked.connect(Next)
        self.next1.clicked.connect(Next)
        self.next2.clicked.connect(Next)
        self.next3.clicked.connect(Next)

        def Previous():
            self.index -= 1
            refresh(self.index)

        self.previous1.clicked.connect(Previous)
        self.previous2.clicked.connect(Previous)
        self.previous3.clicked.connect(Previous)
        self.previous4.clicked.connect(Previous)

        tests = eval(open('../SpeakingDatabase_formatted.txt').read())
        for t in tests:
            self.comboBox.addItem(str("TPO " + t))

        def get_test():
            text = Extract_text.extract(int(self.comboBox.currentText().removeprefix("TPO ")))
            self.Article1.setText(text[0][0])
            self.Article2.setText(text[1][0])
            self.Article3.setText(text[2][0])
            self.Transcript2.setText(text[1][2])
            self.Transcript3.setText(text[2][2])
            self.Transcript4.setText(text[3][1])

        text = Extract_text.extract(int(self.comboBox.currentText().removeprefix("TPO ")))
        self.player2 = QMediaPlayer()
        self.audio2 = QMediaContent(QtCore.QUrl.fromLocalFile(text[1][1]))
        self.audio2_path = text[1][1]
        self.player2.setMedia(self.audio2)
        self.Slider2.setMaximum(int(librosa.get_duration(path=self.audio2_path) * float(1000)))

        self.player3 = QMediaPlayer()
        self.audio3 = QMediaContent(QtCore.QUrl.fromLocalFile(text[2][1]))
        self.audio3_path = text[2][1]
        self.player3.setMedia(self.audio3)
        self.Slider3.setMaximum(int(librosa.get_duration(path=self.audio3_path) * float(1000)))

        self.player4 = QMediaPlayer()
        self.audio4 = QMediaContent(QtCore.QUrl.fromLocalFile(text[3][0]))
        self.audio4_path = text[3][0]
        self.player4.setMedia(self.audio4)
        self.Slider4.setMaximum(int(librosa.get_duration(path=self.audio4_path) * float(1000)))

        def p(player_, value):
            player_.setPosition(value)

        p_2 = lambda: p(self.player2, self.Slider2.value())
        p_3 = lambda: p(self.player3, self.Slider3.value())
        p_4 = lambda: p(self.player4, self.Slider4.value())

        def play(btn, player):
            if btn.isChecked():
                player.play()
            elif not btn.isChecked():
                player.pause()

        play_2 = lambda: play(self.Play2, self.player2)
        play_3 = lambda: play(self.Play3, self.player3)
        play_4 = lambda: play(self.Play4, self.player4)

        self.Slider2.valueChanged.connect(p_2)
        self.Slider2.setValue(self.player2.position())
        self.Slider3.valueChanged.connect(p_3)
        self.Slider3.setValue(self.player3.position())
        self.Slider4.valueChanged.connect(p_4)
        self.Slider4.setValue(self.player4.position())

        self.Play2.clicked.connect(play_2)
        self.Play3.clicked.connect(play_3)
        self.Play4.clicked.connect(play_4)

        get_test()

        self.comboBox.activated.connect(get_test)

        self.Play2.setCheckable(True)
        self.Play3.setCheckable(True)
        self.Play4.setCheckable(True)

        self.Transcript2.hide()
        self.Transcript3.hide()
        self.Transcript4.hide()

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "StackedWidget"))
        self.label_2.setText(_translate("StackedWidget", "TPO: "))
        self.label.setText(
            _translate("StackedWidget", "<html><head/><body><p align=\"center\">Task1</p></body></html>"))
        self.label_5.setText(
            _translate("StackedWidget", "<html><head/><body><p align=\"center\">Task2</p></body></html>"))
        self.label_6.setText(
            _translate("StackedWidget", "<html><head/><body><p align=\"center\">Task3</p></body></html>"))
        self.label_4.setText(
            _translate("StackedWidget", "<html><head/><body><p align=\"center\">Task4</p></body></html>"))


if __name__ == '__main__':
    app = QtWidgets.QApplication([])

    w = QtWidgets.QWidget()
    y = QtWidgets.QStackedWidget(w)
    Ui_StackedWidget().setupUi(y)

    w.show()
    exit(app.exec_())
