# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/Taylor/Desktop/TPO_Scrape/UI/writingGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(705, 563)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.l = QtWidgets.QLabel(Form)
        self.l.setObjectName("l")
        self.horizontalLayout.addWidget(self.l)
        self.cb = QtWidgets.QComboBox(Form)
        self.cb.setObjectName("cb")
        self.horizontalLayout.addWidget(self.cb)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Article = QtWidgets.QTextBrowser(Form)
        self.Article.setObjectName("Article")
        self.verticalLayout.addWidget(self.Article)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Play = QtWidgets.QToolButton(Form)
        self.Play.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/Taylor/Desktop/TPO_Scrape/UI/res/play_btn.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("/Users/Taylor/Desktop/TPO_Scrape/UI/res/pause_btn.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Play.setIcon(icon)
        self.Play.setIconSize(QtCore.QSize(50, 50))
        self.Play.setCheckable(True)
        self.Play.setObjectName("Play")
        self.horizontalLayout_2.addWidget(self.Play)
        self.Slider = QtWidgets.QSlider(Form)
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setObjectName("Slider")
        self.horizontalLayout_2.addWidget(self.Slider)
        self.Timer = QtWidgets.QLabel(Form)
        self.Timer.setObjectName("Timer")
        self.horizontalLayout_2.addWidget(self.Timer)
        self.Show = QtWidgets.QToolButton(Form)
        self.Show.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/Taylor/Desktop/TPO_Scrape/UI/res/down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("/Users/Taylor/Desktop/TPO_Scrape/UI/res/up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Show.setIcon(icon1)
        self.Show.setIconSize(QtCore.QSize(50, 50))
        self.Show.setCheckable(True)
        self.Show.setObjectName("Show")
        self.horizontalLayout_2.addWidget(self.Show)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.Transcript = QtWidgets.QTextBrowser(Form)
        self.Transcript.setObjectName("Transcript")
        self.verticalLayout.addWidget(self.Transcript)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.l.setText(_translate("Form", "TPO: "))
        self.Timer.setText(_translate("Form", "00:00 / 00:00"))
